# Site settings
title: Daniel Sperry
description: Web Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br


sass:
  sass_dir: _sass

# User settings
username: Daniel Sperry
user_title: Web Developer
email: danny.sperry@gmail.com
github_username:  dannysperry

# Google-analytics
google-analytics:
  id: "UA-93991983-1"
# paginate: 5
# paginate_path: /page:num/

exclude: [
  'package.json', 'package-lock.json',
  'yarn.lock', 'node_modules', 'webpack',
  'gulpfile.js', 'config.ru',
  'LICENSE.txt', 'README.md',
  'Gemfile', 'Gemfile.lock'
]

# gems: ['jekyll-paginate']

post:
  coming_soon: Sorry but I have no visible blog entries :(